FROM python:3.9

WORKDIR /app

COPY ./udata-analysis-service/requirements.txt .

RUN pip install -r requirements.txt
RUN pip install csv-detective==0.4.3

RUN pip install flit

COPY ./udata-analysis-service/ .

RUN FLIT_ROOT_INSTALL=1 make install

ENTRYPOINT ["udata-analysis-service", "work"]

