FROM python:3.9

WORKDIR /app

COPY ./udata-datalake-service/requirements.txt .

RUN pip install -r requirements.txt
RUN pip install flit

COPY ./udata-datalake-service/ .

RUN FLIT_ROOT_INSTALL=1 make install

ENTRYPOINT ["udata-datalake-service", "work"]

