FROM python:3.9

WORKDIR /app

COPY ./csvapi/ .

RUN pip install --upgrade pip
# hopefully caches the requirements install layer when upgrading source
RUN pip install -r requirements/install.pip
RUN pip install -e .
RUN pip install Jinja2==3.0.3
RUN pip install Werkzeug==1.0.0
